import React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { FiArrowRight, FiZap, FiTarget, FiTrendingUp, FiCheckCircle } from 'react-icons/fi';
import Button from '../components/ui/Button';
import logo from '../assets/pathfinder-logo.png';
import './Landing.css';

const Landing = () => {
  const navigate = useNavigate();

  const features = [
    {
      icon: <FiTarget />,
      title: 'AI-Powered Roadmaps',
      description: 'Get personalized learning paths generated by advanced AI tailored to your goals and skill level.'
    },
    {
      icon: <FiZap />,
      title: 'Quick & Easy',
      description: 'Create your custom roadmap in minutes.  Just answer a few questions and let AI do the rest.'
    },
    {
      icon: <FiTrendingUp />,
      title: 'Track Progress',
      description: 'Save all your roadmaps and monitor your learning journey in one centralized dashboard.'
    },
  ];

  const steps = [
    {
      number: '1',
      title: 'Set Your Goal',
      description: 'Tell us what you want to learn and your current skill level'
    },
    {
      number: '2',
      title: 'Customize Path',
      description: 'Choose your learning style and time commitment'
    },
    {
      number: '3',
      title: 'Start Learning',
      description: 'Get your personalized roadmap and begin your journey'
    },
  ];

  return (
    <div className="landing-page">
      {/* Navigation */}
      <nav className="landing-nav">
        <div className="landing-nav-container">
          <div className="landing-brand">
            <img src={logo} alt="Pathfinder AI" />
            <span>Pathfinder AI</span>
          </div>
          <div className="landing-nav-links">
            <Link to="/login">Log In</Link>
            <Button onClick={() => navigate('/register')} size="sm">
              Get Started
            </Button>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="hero-section">
        <div className="hero-container">
          <motion.div 
            className="hero-content"
            initial={{ opacity: 0, y:  30 }}
            animate={{ opacity:  1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <h1 className="hero-title">
              Your Personalized Learning Journey{' '}
              <span className="gradient-text">Starts Here</span>
            </h1>
            <p className="hero-description">
              Create AI-powered learning roadmaps tailored to your goals, skill level, 
              and learning style. Start mastering new skills today.
            </p>
            <div className="hero-cta">
              <Button 
                size="lg" 
                icon={<FiArrowRight />}
                onClick={() => navigate('/register')}
              >
                Get Started Free
              </Button>
              <Button 
                size="lg" 
                variant="ghost"
                onClick={() => navigate('/login')}
              >
                Sign In
              </Button>
            </div>
          </motion. div>

          <motion.div 
            className="hero-image"
            initial={{ opacity: 0, x: 30 }}
            animate={{ opacity:  1, x: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            <div className="hero-card-demo">
              <div className="demo-header">
                <div className="demo-dots">
                  <span></span>
                  <span></span>
                  <span></span>
                </div>
              </div>
              <div className="demo-content">
                <h3>🎯 Learn Full-Stack Development</h3>
                <div className="demo-item">
                  <FiCheckCircle /> Master HTML, CSS & JavaScript
                </div>
                <div className="demo-item">
                  <FiCheckCircle /> Build React Applications
                </div>
                <div className="demo-item">
                  <FiCheckCircle /> Learn Backend with Node.js
                </div>
                <div className="demo-item">
                  <FiCheckCircle /> Deploy to Production
                </div>
              </div>
            </div>
          </motion.div>
        </div>

        {/* Floating Shapes */}
        <div className="hero-shapes">
          <div className="hero-shape shape-1"></div>
          <div className="hero-shape shape-2"></div>
          <div className="hero-shape shape-3"></div>
        </div>
      </section>

      {/* Features Section */}
      <section className="features-section">
        <div className="section-container">
          <motion.div 
            className="section-header"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <h2>Why Choose Pathfinder AI? </h2>
            <p>Everything you need to accelerate your learning journey</p>
          </motion.div>

          <div className="features-grid">
            {features.map((feature, index) => (
              <motion.div
                key={index}
                className="feature-card"
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y:  0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
              >
                <div className="feature-icon">{feature.icon}</div>
                <h3>{feature. title}</h3>
                <p>{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="how-it-works-section">
        <div className="section-container">
          <motion.div 
            className="section-header"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y:  0 }}
            viewport={{ once: true }}
          >
            <h2>How It Works</h2>
            <p>Get your personalized roadmap in 3 simple steps</p>
          </motion.div>

          <div className="steps-container">
            {steps.map((step, index) => (
              <motion.div
                key={index}
                className="step-card"
                initial={{ opacity:  0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.15 }}
              >
                <div className="step-number">{step.number}</div>
                <div className="step-content">
                  <h3>{step.title}</h3>
                  <p>{step.description}</p>
                </div>
                {index < steps.length - 1 && (
                  <div className="step-connector"></div>
                )}
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="cta-section">
        <div className="section-container">
          <motion.div 
            className="cta-content"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <h2>Ready to Start Your Journey?</h2>
            <p>Join thousands of learners creating personalized roadmaps</p>
            <Button 
              size="lg" 
              icon={<FiArrowRight />}
              onClick={() => navigate('/register')}
            >
              Create Your Free Roadmap
            </Button>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="landing-footer">
        <div className="footer-container">
          <div className="footer-brand">
            <img src={logo} alt="Pathfinder AI" />
            <span>Pathfinder AI</span>
          </div>
          <p>© 2026 Pathfinder AI. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
};

export default Landing;