import jsPDF from 'jspdf';
import 'jspdf-autotable';

const BRAND_COLOR = '#6366f1';
const TEXT_COLOR = '#1e293b';
const LIGHT_GRAY = '#f1f5f9';
const MEDIUM_GRAY = '#64748b';

/**
 * Generates a beautifully formatted PDF from roadmap data
 * @param {Object} roadmap - The complete roadmap object with metadata and roadmapData
 */
export function generateRoadmapPDF(roadmap) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;

  // Helper function to add page numbers and footer
  const addFooter = (pageNum) => {
    doc.setFontSize(9);
    doc.setTextColor(MEDIUM_GRAY);
    doc.text(
      `Page ${pageNum}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    doc.text(
      'Generated by Pathfinder AI',
      pageWidth / 2,
      pageHeight - 5,
      { align: 'center' }
    );
  };

  // Helper function to check if we need a new page
  const checkPageBreak = (requiredSpace) => {
    if (yPosition + requiredSpace > pageHeight - 25) {
      addFooter(doc.internal.getNumberOfPages());
      doc.addPage();
      yPosition = 20;
      return true;
    }
    return false;
  };

  // ===== HEADER =====
  // Brand background
  doc.setFillColor(BRAND_COLOR);
  doc.rect(0, 0, pageWidth, 35, 'F');
  
  // Title
  doc.setFontSize(24);
  doc.setTextColor(255, 255, 255);
  doc.text('🎯 Pathfinder AI', pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.text('Your Personalized Learning Roadmap', pageWidth / 2, 28, { align: 'center' });
  
  yPosition = 45;

  // ===== METADATA SECTION =====
  doc.setFontSize(16);
  doc.setTextColor(BRAND_COLOR);
  doc.text('Roadmap Overview', 15, yPosition);
  yPosition += 10;

  doc.setFontSize(10);
  doc.setTextColor(TEXT_COLOR);
  
  const metadata = [
    ['Goal:', roadmap.title || roadmap.goal || 'N/A'],
    ['Skill Level:', roadmap.skillLevel || 'N/A'],
    ['Learning Style:', roadmap.learningStyle || 'N/A'],
    ['Time Commitment:', roadmap.timeCommitment || 'N/A'],
    ['Total Days:', roadmap.roadmapData?.timeline?.totalDays?.toString() || 'N/A'],
    ['Date Created:', roadmap.createdAt ? new Date(roadmap.createdAt).toLocaleDateString() : 'N/A']
  ];

  metadata.forEach(([label, value]) => {
    doc.setFont(undefined, 'bold');
    doc.text(label, 15, yPosition);
    doc.setFont(undefined, 'normal');
    doc.text(value, 50, yPosition);
    yPosition += 7;
  });

  yPosition += 5;
  checkPageBreak(30);

  // ===== MILESTONES/PHASES =====
  const milestones = roadmap.roadmapData?.milestones || [];
  
  if (milestones.length > 0) {
    doc.setFontSize(16);
    doc.setTextColor(BRAND_COLOR);
    doc.text('Learning Milestones', 15, yPosition);
    yPosition += 10;

    milestones.forEach((milestone, index) => {
      checkPageBreak(40);

      // Milestone header
      doc.setFillColor(LIGHT_GRAY);
      doc.rect(15, yPosition - 5, pageWidth - 30, 10, 'F');
      
      doc.setFontSize(13);
      doc.setTextColor(BRAND_COLOR);
      doc.setFont(undefined, 'bold');
      doc.text(`${index + 1}. ${milestone.title}`, 17, yPosition);
      doc.setFont(undefined, 'normal');
      yPosition += 10;

      // Description
      doc.setFontSize(10);
      doc.setTextColor(TEXT_COLOR);
      const descLines = doc.splitTextToSize(milestone.description || '', pageWidth - 35);
      doc.text(descLines, 17, yPosition);
      yPosition += descLines.length * 5 + 3;

      // Estimated days
      doc.setTextColor(MEDIUM_GRAY);
      doc.text(`⏱️  Estimated Duration: ${milestone.estimatedDays || 'N/A'} days`, 17, yPosition);
      yPosition += 8;

      // Tasks
      if (milestone.tasks && milestone.tasks.length > 0) {
        doc.setFontSize(11);
        doc.setTextColor(TEXT_COLOR);
        doc.setFont(undefined, 'bold');
        doc.text('Tasks:', 17, yPosition);
        doc.setFont(undefined, 'normal');
        yPosition += 6;

        milestone.tasks.forEach((task) => {
          checkPageBreak(10);
          doc.setFontSize(10);
          doc.text('☐', 20, yPosition);
          const taskLines = doc.splitTextToSize(task, pageWidth - 45);
          doc.text(taskLines, 27, yPosition);
          yPosition += taskLines.length * 5 + 2;
        });
        yPosition += 3;
      }

      // Milestone-level resources (from upgrade #2)
      if (milestone.resources && milestone.resources.length > 0) {
        checkPageBreak(15);
        doc.setFontSize(11);
        doc.setTextColor(TEXT_COLOR);
        doc.setFont(undefined, 'bold');
        doc.text('Resources for this milestone:', 17, yPosition);
        doc.setFont(undefined, 'normal');
        yPosition += 6;

        milestone.resources.forEach((resource) => {
          checkPageBreak(8);
          doc.setFontSize(9);
          const icon = getResourceIcon(resource.type);
          doc.text(`${icon} ${resource.name} (${resource.type})`, 20, yPosition);
          doc.setTextColor(BRAND_COLOR);
          doc.textWithLink(resource.link, 25, yPosition + 4, { url: resource.link });
          doc.setTextColor(TEXT_COLOR);
          yPosition += 9;
        });
        yPosition += 3;
      }

      yPosition += 5;
    });
  }

  // ===== GLOBAL RESOURCES =====
  const resources = roadmap.roadmapData?.resources || [];
  if (resources.length > 0) {
    checkPageBreak(30);
    
    doc.setFontSize(16);
    doc.setTextColor(BRAND_COLOR);
    doc.text('Additional Resources', 15, yPosition);
    yPosition += 10;

    resources.forEach((resource) => {
      checkPageBreak(10);
      doc.setFontSize(10);
      doc.setTextColor(TEXT_COLOR);
      const icon = getResourceIcon(resource.type);
      doc.text(`${icon} ${resource.name} (${resource.type})`, 17, yPosition);
      doc.setFontSize(9);
      doc.setTextColor(BRAND_COLOR);
      doc.textWithLink(resource.link, 20, yPosition + 5, { url: resource.link });
      doc.setTextColor(TEXT_COLOR);
      yPosition += 12;
    });
    yPosition += 5;
  }

  // ===== TIPS SECTION =====
  const tips = roadmap.roadmapData?.tips || [];
  if (tips.length > 0) {
    checkPageBreak(30);
    
    doc.setFontSize(16);
    doc.setTextColor(BRAND_COLOR);
    doc.text('Learning Tips', 15, yPosition);
    yPosition += 10;

    tips.forEach((tip, index) => {
      checkPageBreak(15);
      doc.setFontSize(10);
      doc.setTextColor(TEXT_COLOR);
      doc.text(`💡 ${tip}`, 17, yPosition, { maxWidth: pageWidth - 35 });
      yPosition += 10;
    });
  }

  // Add footer to last page
  addFooter(doc.internal.getNumberOfPages());

  // Generate filename
  const filename = `${roadmap.title || 'roadmap'}_${new Date().toISOString().split('T')[0]}.pdf`;
  
  // Save the PDF
  doc.save(filename);
}

/**
 * Get emoji icon for resource type
 */
function getResourceIcon(type) {
  const icons = {
    'Video': '🎥',
    'Article': '📖',
    'Course': '💻',
    'Documentation': '📄',
    'Book': '📕',
    'Tool': '🔧',
    'Repository': '🗂️'
  };
  return icons[type] || '📎';
}
